import React from 'react'
import './features.css'
import searchLogo from '../images/1.png'
import arrowLogo from '../images/2.png'
import standOutLogo from '../images/2.svg'

const features = () => {
  return (
    <div className='featuresParent'>
        
        <div className='search-feature'>
            <img src={searchLogo} alt='searchLogo'/>
            <span style={{color:"#1A181E", marginTop:"15px",fontSize:"22px", fontWeight:"600"}}>Search</span>
            <p>Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</p>
        </div>
        <div className='search-feature'>
            <img src={arrowLogo} alt='arrowLogo'/>
            <span style={{color:"#1A181E", marginTop:"15px", fontSize:"22px", fontWeight:"600"}}>Select</span>
            <p>Choose from thousands of options generated by the slogan maker that fit your needs.</p>
        </div>
        <div className='search-feature'>
            <img src={standOutLogo} alt='standOutLogo'/>
            <span style={{color:"#1A181E", marginTop:"15px", fontSize:"22px", fontWeight:"600"}}>Stand out</span>
            <p>Congrats on your new slogan. It's time to win the world!</p>
        </div>
    </div>
  )
}

export default features